---

- name: Remove service symlink
  become: true
  ansible.builtin.file:
    path: "/home/{{ user }}/.config/systemd/user/graphical-session.target.wants/ulauncher.service"
    state: absent

# TODO remove custom gnome shortcut in case of wayland

...
