---

- name: Comment on no tasks
  ansible.builtin.debug:
    msg: "Since this role only apllies settings and doesn't install packages - there's no absent logic to handle"

# TODO remove custom gnome shortcut in case of wayland

...
